### PR TITLE
upgrade joi version to 17

### PR DESCRIPTION
**Pull request by phpstudyone**
## Types of changes

- [ ] Documentation only (no changes to either `lib/` or `test/` files)
- [ ] Bug fix (non-breaking change which fixes an issue. you didn't modify existing tests)
- [ ] New feature (non-breaking change which adds functionality. you added at least one new test)
- [ ] Breaking change (fix or feature that would cause existing functionality to change. you had to modify existing tests.)

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/xogroup/felicity/blob/master/.github/CONTRIBUTING.md) document.
- [ ] My code follows the [Hapi.js style guide](https://github.com/hapijs/contrib/blob/master/Style.md).
- [ ] I have updated the documentation as needed.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by WesTyler** [comment]
Thanks so much! I'm taking a look at this now :)

**Comment by WesTyler** [comment]
I replaced the `flat` npm package with the native Node.js [`Array.prototype.flat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) method.

I've also updated the object key spacing linting to align with hapi standards, even though I have gotten used to the aligned colons.

I have a work in progress commit to do some general code cleanup around improvements Joi made, and to bring code coverage back up to 100%. I will wrap that commit up in the morning (my time zone :) ) and then will publish out v6.0.0

Thanks again for all of your hard work getting this update done!

**Comment by phpstudyone** [comment]
> I replaced the `flat` npm package with the native Node.js [`Array.prototype.flat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) method.
> 
> I've also updated the object key spacing linting to align with hapi standards, even though I have gotten used to the aligned colons.
> 
> I have a work in progress commit to do some general code cleanup around improvements Joi made, and to bring code coverage back up to 100%. I will wrap that commit up in the morning (my time zone :) ) and then will publish out v6.0.0
> 
> Thanks again for all of your hard work getting this update done!

The `flat` function was added in node11. Using the native flat function will cause the node10 version to not work properly and prompt: flat is undefined

**Comment by WesTyler** [comment]
I think that's okay. Node@10 has been in maintenance mode for over a year and will be no longer supported at any level in a few weeks. 

I'll specify the supported versions of Node.js in the package.json/README/release notes.

**Comment by WesTyler** [comment]
Also just to mention, Joi@17 is also using language syntax not supported in Node@10, so that will break in that environment anyways.

**Pull request merged**
